version: "3"  # optional since v1.27.0

services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Geheim123"
    ports:
      - "1433:1433"	    # hier nog wel portbinding, omdat we de database van buitenaf willen benaderen via sql management studio (en dotnet ef update)
    volumes: 
      - sqlvolume:/var/opt/mssql    #add data volume zodat data bewaard blijft als container verwijderd wordt
  mongodb-server:
    image: mongo
    ports:
      - "27017:27017"   # hier nog wel portbinding, omdat we de database van buitenaf willen benaderen via MongoDB Compass
    volumes: 
      - mongodbdata:/data/db
  eggtypeservice-api:
    # image: joost1982/eggtypeservice 		# dit kan ook (misschien zelfs beter zodat wijzigingen ook meegenomen worden): 		build: .
    build: ./EggTypeService/EggTypeService/.      # nb: maakt gebruik van Dockerfile in die map!
    environment:
      ConnectionStrings__MongoDbConnection: mongodb://mongodb-server:27017
    #ports:
    #  - "8080:80" # nb: geen port binding hier! server is van buiten niet meer direct te benaderen (gaat via nginx api gateway)
    expose:
      - "80"    
  flockservice-api:
    build: ./FlockService/FlockService/.
    environment:
      ConnectionStrings__FlockConnectionDocker: Server=ms-sql-server,1433;Database=FlockDb;User Id=SA;Password=Geheim123;
    #ports:
    #  - "8081:80" # nb: geen port binding hier! server is van buiten niet meer direct te benaderen (gaat via nginx api gateway)
    expose:
      - "80"    

volumes:
  mongodbdata:
#    name: my_volume_001
  sqlvolume: