apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eggstatestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
scopes:                # restrict the services that can subscribe
  - eggtypeservice-api  
